# Regenerates website/gallery-data.js from the images in
# website/assets/gallery/2024 and /2025.
# Run from anywhere:  powershell -File website/build-gallery.ps1

$ErrorActionPreference = 'Stop'
$root = $PSScriptRoot                          # ...\website
$exts = @('.jpg', '.jpeg', '.png', '.webp')

function Get-Year-Images([string]$year) {
    $dir = Join-Path $root "assets\gallery\$year"
    if (-not (Test-Path $dir)) { return @() }
    Get-ChildItem -Path $dir -File |
        Where-Object { $exts -contains $_.Extension.ToLower() } |
        Sort-Object Name |
        ForEach-Object { "assets/gallery/$year/$($_.Name)" }
}

$data = [ordered]@{
    '2025' = @(Get-Year-Images '2025')
    '2024' = @(Get-Year-Images '2024')
}

# Build the JS file by hand so output is clean and diff-friendly.
$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('/* AUTO-GENERATED by build-gallery.ps1 - do not edit by hand. */')
[void]$sb.AppendLine('window.GALLERY_DATA = {')
$years = @($data.Keys)
for ($i = 0; $i -lt $years.Count; $i++) {
    $year = $years[$i]
    $imgs = $data[$year]
    [void]$sb.AppendLine("  ""$year"": [")
    for ($j = 0; $j -lt $imgs.Count; $j++) {
        $comma = if ($j -lt $imgs.Count - 1) { ',' } else { '' }
        $val = $imgs[$j] -replace '"', '\"'
        [void]$sb.AppendLine("    ""$val""$comma")
    }
    $tail = if ($i -lt $years.Count - 1) { '],' } else { ']' }
    [void]$sb.AppendLine("  $tail")
}
[void]$sb.AppendLine('};')

$out = Join-Path $root 'gallery-data.js'
[System.IO.File]::WriteAllText($out, $sb.ToString(), [System.Text.UTF8Encoding]::new($false))

Write-Host "Wrote $out"
Write-Host ("  2025: {0} photo(s)" -f $data['2025'].Count)
Write-Host ("  2024: {0} photo(s)" -f $data['2024'].Count)
