/* ============================================================
   Gallery rendering + lightbox.
   Reads window.GALLERY_DATA (generated by build-gallery.ps1)
   and fills every .gallery-grid[data-year] with photo tiles.
   ============================================================ */
(function () {
  'use strict';

  var DATA = window.GALLERY_DATA || {};
  var grids = Array.prototype.slice.call(document.querySelectorAll('.gallery-grid[data-year]'));
  if (!grids.length) return;

  // Per-year image lists, so the lightbox can navigate within a set.
  var sets = {};

  grids.forEach(function (grid) {
    var year = grid.getAttribute('data-year');
    var label = grid.getAttribute('data-label') || ('AFCON NT ' + year);
    var imgs = (DATA[year] || []).slice();
    sets[year] = { label: label, imgs: imgs };

    // Count badge in the section intro.
    var countEl = document.querySelector('.gallery-count[data-count-for="' + year + '"]');
    if (countEl) {
      countEl.textContent = imgs.length
        ? imgs.length + (imgs.length === 1 ? ' photo' : ' photos')
        : '';
    }

    if (!imgs.length) {
      var empty = document.createElement('div');
      empty.className = 'gallery-empty';
      empty.innerHTML = '<strong>Photos coming soon</strong>' +
        '<span>We’re curating the ' + label + ' gallery. Check back shortly.</span>';
      grid.appendChild(empty);
      return;
    }

    var frag = document.createDocumentFragment();
    imgs.forEach(function (src, i) {
      var fig = document.createElement('figure');
      fig.className = 'gallery-card';
      fig.setAttribute('role', 'button');
      fig.setAttribute('tabindex', '0');
      fig.setAttribute('aria-label', label + ' photo ' + (i + 1) + ' of ' + imgs.length);
      fig.dataset.year = year;
      fig.dataset.index = String(i);

      var img = document.createElement('img');
      img.src = src;
      img.alt = label + ' — photo ' + (i + 1);
      img.loading = 'lazy';
      img.decoding = 'async';
      img.addEventListener('load', function () { fig.classList.add('is-loaded'); });
      // If a cached image is already complete, reveal immediately.
      if (img.complete) fig.classList.add('is-loaded');

      var shade = document.createElement('span');
      shade.className = 'gallery-shade';
      shade.textContent = year;

      fig.appendChild(img);
      fig.appendChild(shade);
      frag.appendChild(fig);
    });
    grid.appendChild(frag);
  });

  /* ---------- Lightbox ---------- */
  var lb = document.getElementById('lightbox');
  if (!lb) return;
  var lbImg = document.getElementById('lbImg');
  var lbMeta = document.getElementById('lbMeta');
  var reduceMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;

  var current = { year: null, index: 0 };
  var lastFocus = null;

  function show(year, index) {
    var set = sets[year];
    if (!set || !set.imgs.length) return;
    var n = set.imgs.length;
    index = ((index % n) + n) % n; // wrap
    current.year = year;
    current.index = index;
    lbImg.src = set.imgs[index];
    lbImg.alt = set.label + ' — photo ' + (index + 1);
    lbMeta.textContent = set.label + '  ·  ' + (index + 1) + ' / ' + n;
  }

  function openLb(year, index) {
    lastFocus = document.activeElement;
    show(year, index);
    lb.hidden = false;
    requestAnimationFrame(function () { lb.classList.add('open'); });
    document.body.classList.add('modal-locked');
    var closeBtn = lb.querySelector('[data-lb-close]');
    if (closeBtn) closeBtn.focus({ preventScroll: true });
  }

  function closeLb() {
    lb.classList.remove('open');
    document.body.classList.remove('modal-locked');
    setTimeout(function () {
      lb.hidden = true;
      lbImg.removeAttribute('src');
      if (lastFocus && typeof lastFocus.focus === 'function') lastFocus.focus({ preventScroll: true });
    }, reduceMotion ? 0 : 280);
  }

  function step(dir) { show(current.year, current.index + dir); }

  // Open from a tile (click or keyboard).
  grids.forEach(function (grid) {
    grid.addEventListener('click', function (e) {
      var card = e.target.closest('.gallery-card');
      if (!card || !grid.contains(card)) return;
      openLb(card.dataset.year, parseInt(card.dataset.index, 10));
    });
    grid.addEventListener('keydown', function (e) {
      if (e.key !== 'Enter' && e.key !== ' ') return;
      var card = e.target.closest('.gallery-card');
      if (!card) return;
      e.preventDefault();
      openLb(card.dataset.year, parseInt(card.dataset.index, 10));
    });
  });

  lb.querySelector('[data-lb-close]').addEventListener('click', closeLb);
  lb.querySelector('[data-lb-prev]').addEventListener('click', function () { step(-1); });
  lb.querySelector('[data-lb-next]').addEventListener('click', function () { step(1); });

  // Click on the dimmed backdrop (not the image/buttons) closes.
  lb.addEventListener('click', function (e) {
    if (e.target === lb || e.target.classList.contains('lb-stage')) closeLb();
  });

  document.addEventListener('keydown', function (e) {
    if (lb.hidden) return;
    if (e.key === 'Escape') closeLb();
    else if (e.key === 'ArrowLeft') step(-1);
    else if (e.key === 'ArrowRight') step(1);
  });
})();
